#pragma once
#include <cstdint>

/**
 * @file polyglot_keys.hpp
 * @brief Precomputed random keys for Polyglot Zobrist hashing.
 */

namespace Polyglot {
    /**
     * @brief Array of 781 64-bit random numbers used to compute Polyglot hashes.
     * 
     * This matches the exact set of random numbers generated by the original
     * Polyglot hashing algorithm for compatibility with standard .bin books.
     */
    extern const uint64_t Random64[781];
}
